"""Structured literal lowering for generated VM Lua.

The regular obfuscation passes parse their complete input on every stage.  VM
output is already compiler-generated and can be several megabytes long, so the
literal-only stages keep a small fragment IR instead: Tree-sitter identifies
the original literals once, each configured emitter lowers matching fragments,
and the final Lua text is rendered once.  Literals generated by one stage stay
typed and are therefore visible to later stages.
"""
from __future__ import annotations

import random
import re
import time
from dataclasses import dataclass

import tree_sitter as ts

from ..passes.boolean_obfuscation import generate_rand_xor
from ..passes.base import Replacement
from ..passes.number_obfuscation import NumberObfuscationPass
from ..passes.string_obfuscation import _CHUNK_SIZE, parse_lua_string
from ..passes.ts_utils import _LANG, parse


EMITTER_PASS_NAMES = frozenset({"number_obf", "string_obf", "boolean_obf"})

_LITERAL_QUERY = ts.Query(
    _LANG,
    "(number) @number (string) @string [(true) (false)] @boolean",
)


@dataclass(frozen=True, slots=True)
class NumberLiteral:
    token: str
    eligible: bool = True


@dataclass(frozen=True, slots=True)
class StringLiteral:
    token: str


@dataclass(frozen=True, slots=True)
class BooleanLiteral:
    value: bool


Fragment = str | NumberLiteral | StringLiteral | BooleanLiteral


_GENERATED_NUMBER_RE = re.compile(
    r"(?<![A-Za-z0-9_.])"
    r"(?:"
    r"0[xX](?:(?:[0-9A-Fa-f]+(?:\.[0-9A-Fa-f]*)?)|(?:\.[0-9A-Fa-f]+))"
    r"(?:[pP][+-]?\d+)?"
    r"|"
    r"(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eE][+-]?\d+)?"
    r")"
    r"(?![A-Za-z0-9_])"
)

_EXACT_HEX64_RE = re.compile(r"0[xX][0-9A-Fa-f]{16}")
_EXACT_GRAPH_REGION_RE = re.compile(
    r"--\[\[KARITY_EXACT_BEGIN\]\].*?--\[\[KARITY_EXACT_END\]\]",
    re.DOTALL,
)


def _append_raw(parts: list[Fragment], text: str) -> None:
    if not text:
        return
    # Keep coalescing bounded. Identifier plans can create 80k+ adjacent raw
    # fragments; repeatedly concatenating them into one ever-growing string is
    # quadratic even though the final renderer already joins in linear time.
    if (
        parts
        and isinstance(parts[-1], str)
        and len(parts[-1]) + len(text) <= 4096
    ):
        parts[-1] += text
    else:
        parts.append(text)


def _split_generated_numbers(expr: str) -> list[Fragment]:
    """Tokenize controlled NumberObfuscationPass output for later layers.

    Number expressions contain no strings or comments.  Keeping their numeric
    leaves typed lets a second configured number stage reproduce the old
    parse-after-replacement layering without parsing the whole VM again.
    """
    parts: list[Fragment] = []
    pos = 0
    for match in _GENERATED_NUMBER_RE.finditer(expr):
        _append_raw(parts, expr[pos:match.start()])
        parts.append(NumberLiteral(match.group(0)))
        pos = match.end()
    _append_raw(parts, expr[pos:])
    return parts


def _inside_string_char(node, ctx, cache: dict[int, bool]) -> bool:
    visited: list[int] = []
    current = node.parent
    while current is not None:
        cached = cache.get(current.id)
        if cached is not None:
            for node_id in visited:
                cache[node_id] = cached
            return cached
        visited.append(current.id)
        if current.type == "function_call":
            result = bool(
                current.children
                and ctx.text(current.children[0]) == "string.char"
            )
            for node_id in visited:
                cache[node_id] = result
            return result
        if current.type in ("assignment_statement", "return_statement"):
            for node_id in visited:
                cache[node_id] = False
            return False
        current = current.parent
    for node_id in visited:
        cache[node_id] = False
    return False


def _parse_fragments(
    source: str,
    ctx,
    replacements: list[Replacement],
    literal_nodes: list | None = None,
) -> tuple[list[Fragment], int]:
    exact_graph_ranges = [
        (match.start(), match.end() - 1)
        for match in _EXACT_GRAPH_REGION_RE.finditer(source)
    ]
    exact_graph_index = 0

    def in_exact_graph(start: int, end: int) -> bool:
        nonlocal exact_graph_index
        while (
            exact_graph_index < len(exact_graph_ranges)
            and exact_graph_ranges[exact_graph_index][1] < start
        ):
            exact_graph_index += 1
        return (
            exact_graph_index < len(exact_graph_ranges)
            and exact_graph_ranges[exact_graph_index][0] <= start
            and end <= exact_graph_ranges[exact_graph_index][1]
        )

    if literal_nodes is None:
        captures = ts.QueryCursor(_LITERAL_QUERY).captures(ctx.root)
        if isinstance(captures, dict):
            literals = [node for nodes in captures.values() for node in nodes]
        else:
            literals = [node for node, _ in captures]
        literals.sort(key=lambda node: node.start_byte)
    else:
        literals = literal_nodes

    # Identifier plans and AST captures are each source ordered. Keep them as
    # two streams instead of allocating and sorting a combined 100k+ event
    # array. Insertions sort before consuming replacements at the same offset.
    replacement_events = sorted(
        replacements,
        key=lambda item: (item.start, 0 if item.end < item.start else 1),
    )

    parts: list[Fragment] = []
    pos = 0
    captured_count = 0
    string_char_cache: dict[int, bool] = {}
    replacement_index = 0
    literal_index = 0
    literal_event = None
    while (
        replacement_index < len(replacement_events)
        or literal_event is not None
        or literal_index < len(literals)
    ):
        if literal_event is None and literal_index < len(literals):
            literal = literals[literal_index]
            literal_index += 1
            literal_event = (ctx.cs(literal), ctx.ce(literal), literal)

        if literal_event is None:
            payload = replacement_events[replacement_index]
            replacement_index += 1
            start, end = payload.start, payload.end
        elif replacement_index >= len(replacement_events):
            start, end, payload = literal_event
            literal_event = None
        else:
            replacement = replacement_events[replacement_index]
            literal_start, literal_end, literal = literal_event
            replacement_key = (
                replacement.start,
                0 if replacement.end < replacement.start else 1,
            )
            if replacement_key < (literal_start, 2):
                payload = replacement
                replacement_index += 1
                start, end = replacement.start, replacement.end
            else:
                start, end, payload = literal_start, literal_end, literal
                literal_event = None

        if start < pos:
            # A consuming identifier/global replacement can cover a literal
            # event. The old implementation filtered those through a second
            # ranges list; skipping lazily avoids allocating that list and a
            # second 300k+ literal event array.
            if not isinstance(payload, Replacement):
                continue
            raise RuntimeError(
                f"overlapping VM output event at {start}:{end}, previous end={pos - 1}"
            )
        if start > pos:
            parts.append(source[pos:start])

        if isinstance(payload, Replacement):
            if payload.new_text:
                parts.append(payload.new_text)
            if end >= start:
                pos = end + 1
            else:
                pos = start
            continue

        node = payload
        token = source[start:end + 1]
        if node.type == "number":
            parts.append(NumberLiteral(
                token,
                not _inside_string_char(node, ctx, string_char_cache)
                and _EXACT_HEX64_RE.fullmatch(token) is None
                and not in_exact_graph(start, end),
            ))
        elif node.type == "string":
            parts.append(StringLiteral(token))
        else:
            parts.append(BooleanLiteral(node.type == "true"))
        captured_count += 1
        pos = end + 1
    if pos < len(source):
        parts.append(source[pos:])
    return parts, captured_count


def _emit_string(token: str) -> list[Fragment]:
    data = parse_lua_string(token)
    if not data:
        return [StringLiteral('""')]

    parts: list[Fragment] = []
    for chunk_index, offset in enumerate(range(0, len(data), _CHUNK_SIZE)):
        if chunk_index:
            _append_raw(parts, "..")
        _append_raw(parts, "string.char(")
        chunk = data[offset:offset + _CHUNK_SIZE]
        for index, value in enumerate(chunk):
            if index:
                _append_raw(parts, ",")
            first = random.randint(10_000, 9_999_999)
            _append_raw(parts, "(")
            parts.append(NumberLiteral(str(first)))
            _append_raw(parts, "~")
            parts.append(NumberLiteral(str(first ^ value)))
            _append_raw(parts, ")")
        _append_raw(parts, ")")
    return parts


def _emit_boolean(value: bool) -> list[Fragment]:
    first, second, xor = generate_rand_xor()
    expected = xor if value else xor + 1
    return [
        "((", NumberLiteral(str(first)), "~",
        NumberLiteral(str(second)), ")==",
        NumberLiteral(str(expected)), ")",
    ]


def _render(parts: list[Fragment]) -> str:
    rendered: list[str] = []
    for part in parts:
        if isinstance(part, str):
            rendered.append(part)
        elif isinstance(part, NumberLiteral):
            rendered.append(part.token)
        elif isinstance(part, StringLiteral):
            rendered.append(part.token)
        else:
            rendered.append("true" if part.value else "false")
    return "".join(rendered)


def emit_vm_literals(
    source: str,
    pass_names: list[str],
    *,
    ctx=None,
    replacements: list[Replacement] | None = None,
    literal_nodes: list | None = None,
) -> tuple[str, list[dict]]:
    """Apply identifier plans and literal stages over one syntax context."""
    stages = [name for name in pass_names if name in EMITTER_PASS_NAMES]
    replacements = replacements or []
    if not stages and not replacements:
        return source, []

    parse_start = time.perf_counter()
    parse_count = 0
    if ctx is None:
        ctx = parse(source)
        parse_count = 1
    parts, literal_count = _parse_fragments(
        source, ctx, replacements, literal_nodes,
    )
    details: list[dict] = [{
        "phase": (
            "vm_output:literal_parse" if parse_count
            else "vm_output:literal_capture"
        ),
        "class": "VmLiteralEmitter",
        "elapsed": round(time.perf_counter() - parse_start, 6),
        "input_bytes": len(source.encode("utf-8")),
        "literal_count": literal_count,
        "parser": "treesitter",
        "parse_count": parse_count,
        "planned_replacements": len(replacements),
        "capture_source": "rename_traversal" if literal_nodes is not None else "query",
    }]

    number_emitter = NumberObfuscationPass()
    for stage_index, name in enumerate(stages):
        stage_start = time.perf_counter()
        output: list[Fragment] = []
        replacements = 0
        retokenize_generated_numbers = (
            name == "number_obf"
            and "number_obf" in stages[stage_index + 1:]
        )

        for part in parts:
            if name == "string_obf" and isinstance(part, StringLiteral):
                output.extend(_emit_string(part.token))
                replacements += 1
            elif name == "boolean_obf" and isinstance(part, BooleanLiteral):
                output.extend(_emit_boolean(part.value))
                replacements += 1
            elif (
                name == "number_obf"
                and isinstance(part, NumberLiteral)
                and part.eligible
            ):
                expression = number_emitter.obfuscate_token(part.token)
                if retokenize_generated_numbers:
                    output.extend(_split_generated_numbers(expression))
                else:
                    # The generated leaves only need to stay typed when a
                    # later number stage will wrap them again. The terminal
                    # stage can emit raw Lua directly, avoiding a regex scan
                    # and several fragment allocations per replacement.
                    _append_raw(output, expression)
                replacements += 1
            else:
                output.append(part)

        parts = output
        details.append({
            "phase": f"vm_output:{name}",
            "class": "VmLiteralEmitter",
            "elapsed": round(time.perf_counter() - stage_start, 6),
            "replacements": replacements,
            "backend": "structured_emitter",
            **(
                {"retokenized_generated_numbers": retokenize_generated_numbers}
                if name == "number_obf"
                else {}
            ),
        })

    render_start = time.perf_counter()
    rendered = _render(parts)
    details.append({
        "phase": "vm_output:literal_render",
        "class": "VmLiteralEmitter",
        "elapsed": round(time.perf_counter() - render_start, 6),
        "output_bytes": len(rendered.encode("utf-8")),
    })
    return rendered, details
