"""Structured literal lowering for generated VM Lua.

The regular obfuscation passes parse their complete input on every stage.  VM
output is already compiler-generated and can be several megabytes long, so the
literal-only stages keep a small fragment IR instead: Tree-sitter identifies
the original literals once, each configured emitter lowers matching fragments,
and the final Lua text is rendered once.  Literals generated by one stage stay
typed and are therefore visible to later stages.
"""
from __future__ import annotations

import random
import re
import time
from dataclasses import dataclass

import tree_sitter as ts

from ..passes.boolean_obfuscation import generate_rand_xor
from ..passes.number_obfuscation import NumberObfuscationPass
from ..passes.string_obfuscation import _CHUNK_SIZE, parse_lua_string
from ..passes.ts_utils import _LANG, _PARSER


EMITTER_PASS_NAMES = frozenset({"number_obf", "string_obf", "boolean_obf"})

_LITERAL_QUERY = ts.Query(
    _LANG,
    "(number) @number (string) @string [(true) (false)] @boolean",
)


@dataclass(frozen=True)
class Raw:
    text: str


@dataclass(frozen=True)
class NumberLiteral:
    token: str
    eligible: bool = True


@dataclass(frozen=True)
class StringLiteral:
    token: str


@dataclass(frozen=True)
class BooleanLiteral:
    value: bool


Fragment = Raw | NumberLiteral | StringLiteral | BooleanLiteral


_GENERATED_NUMBER_RE = re.compile(
    r"(?<![A-Za-z0-9_.])"
    r"(?:"
    r"0[xX](?:(?:[0-9A-Fa-f]+(?:\.[0-9A-Fa-f]*)?)|(?:\.[0-9A-Fa-f]+))"
    r"(?:[pP][+-]?\d+)?"
    r"|"
    r"(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eE][+-]?\d+)?"
    r")"
    r"(?![A-Za-z0-9_])"
)


def _append_raw(parts: list[Fragment], text: str) -> None:
    if not text:
        return
    if parts and isinstance(parts[-1], Raw):
        parts[-1] = Raw(parts[-1].text + text)
    else:
        parts.append(Raw(text))


def _split_generated_numbers(expr: str) -> list[Fragment]:
    """Tokenize controlled NumberObfuscationPass output for later layers.

    Number expressions contain no strings or comments.  Keeping their numeric
    leaves typed lets a second configured number stage reproduce the old
    parse-after-replacement layering without parsing the whole VM again.
    """
    parts: list[Fragment] = []
    pos = 0
    for match in _GENERATED_NUMBER_RE.finditer(expr):
        _append_raw(parts, expr[pos:match.start()])
        parts.append(NumberLiteral(match.group(0)))
        pos = match.end()
    _append_raw(parts, expr[pos:])
    return parts


def _node_text(data: bytes, node) -> str:
    return data[node.start_byte:node.end_byte].decode("utf-8")


def _inside_string_char(node, data: bytes) -> bool:
    current = node.parent
    while current is not None:
        if current.type == "function_call":
            return bool(
                current.children
                and _node_text(data, current.children[0]) == "string.char"
            )
        if current.type in ("assignment_statement", "return_statement"):
            return False
        current = current.parent
    return False


def _parse_fragments(source: str) -> tuple[list[Fragment], int]:
    data = source.encode("utf-8")
    tree = _PARSER.parse(data)
    captures = ts.QueryCursor(_LITERAL_QUERY).captures(tree.root_node)
    if isinstance(captures, dict):
        literals = [node for nodes in captures.values() for node in nodes]
    else:
        literals = [node for node, _ in captures]
    literals.sort(key=lambda node: node.start_byte)

    parts: list[Fragment] = []
    pos = 0
    for node in literals:
        start = node.start_byte
        end = node.end_byte
        if start < pos:
            continue
        _append_raw(parts, data[pos:start].decode("utf-8"))
        token = data[start:end].decode("utf-8")
        if node.type == "number":
            parts.append(NumberLiteral(token, not _inside_string_char(node, data)))
        elif node.type == "string":
            parts.append(StringLiteral(token))
        else:
            parts.append(BooleanLiteral(node.type == "true"))
        pos = end
    _append_raw(parts, data[pos:].decode("utf-8"))
    return parts, len(literals)


def _emit_string(token: str) -> list[Fragment]:
    data = parse_lua_string(token)
    if not data:
        return [StringLiteral('""')]

    parts: list[Fragment] = []
    for chunk_index, offset in enumerate(range(0, len(data), _CHUNK_SIZE)):
        if chunk_index:
            _append_raw(parts, "..")
        _append_raw(parts, "string.char(")
        chunk = data[offset:offset + _CHUNK_SIZE]
        for index, value in enumerate(chunk):
            if index:
                _append_raw(parts, ",")
            first = random.randint(10_000, 9_999_999)
            _append_raw(parts, "(")
            parts.append(NumberLiteral(str(first)))
            _append_raw(parts, "~")
            parts.append(NumberLiteral(str(first ^ value)))
            _append_raw(parts, ")")
        _append_raw(parts, ")")
    return parts


def _emit_boolean(value: bool) -> list[Fragment]:
    first, second, xor = generate_rand_xor()
    expected = xor if value else xor + 1
    return [
        Raw("(("), NumberLiteral(str(first)), Raw("~"),
        NumberLiteral(str(second)), Raw(")=="),
        NumberLiteral(str(expected)), Raw(")"),
    ]


def _render(parts: list[Fragment]) -> str:
    rendered: list[str] = []
    for part in parts:
        if isinstance(part, Raw):
            rendered.append(part.text)
        elif isinstance(part, NumberLiteral):
            rendered.append(part.token)
        elif isinstance(part, StringLiteral):
            rendered.append(part.token)
        else:
            rendered.append("true" if part.value else "false")
    return "".join(rendered)


def emit_vm_literals(
    source: str,
    pass_names: list[str],
) -> tuple[str, list[dict]]:
    """Apply configured literal stages over one parsed VM fragment stream."""
    stages = [name for name in pass_names if name in EMITTER_PASS_NAMES]
    if not stages:
        return source, []

    parse_start = time.perf_counter()
    parts, literal_count = _parse_fragments(source)
    details: list[dict] = [{
        "phase": "vm_output:literal_parse",
        "class": "VmLiteralEmitter",
        "elapsed": round(time.perf_counter() - parse_start, 6),
        "input_bytes": len(source.encode("utf-8")),
        "literal_count": literal_count,
        "parser": "treesitter",
        "parse_count": 1,
    }]

    number_emitter = NumberObfuscationPass()
    for name in stages:
        stage_start = time.perf_counter()
        output: list[Fragment] = []
        replacements = 0

        for part in parts:
            if name == "string_obf" and isinstance(part, StringLiteral):
                output.extend(_emit_string(part.token))
                replacements += 1
            elif name == "boolean_obf" and isinstance(part, BooleanLiteral):
                output.extend(_emit_boolean(part.value))
                replacements += 1
            elif (
                name == "number_obf"
                and isinstance(part, NumberLiteral)
                and part.eligible
            ):
                output.extend(_split_generated_numbers(
                    number_emitter.obfuscate_token(part.token)
                ))
                replacements += 1
            else:
                output.append(part)

        parts = output
        details.append({
            "phase": f"vm_output:{name}",
            "class": "VmLiteralEmitter",
            "elapsed": round(time.perf_counter() - stage_start, 6),
            "replacements": replacements,
            "backend": "structured_emitter",
        })

    render_start = time.perf_counter()
    rendered = _render(parts)
    details.append({
        "phase": "vm_output:literal_render",
        "class": "VmLiteralEmitter",
        "elapsed": round(time.perf_counter() - render_start, 6),
        "output_bytes": len(rendered.encode("utf-8")),
    })
    return rendered, details
