from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from obfuscator.registry import (  # noqa: E402
    PASS_DESCRIPTIONS,
    PASS_REGISTRY,
    VM_OPTION_DOCS,
    get_pass_contexts,
)


OUTPUT = ROOT_DIR / "docs" / "configuration.md"

VM_DETAILS = """\
Integer arithmetic, bitwise, shift, and unary handlers use build-specific function
DAG banks with randomized topological layouts, sparse selectors, and equivalent
mixed boolean-arithmetic expressions. The active graph is selected from the VM id,
instruction position, and accumulated diffusion state.

VM-internal CALL, TAILCALL, and RETURN transitions use heap continuation frames
instead of recursively returning through the host Lua stack. Calls and returns pass
through build-specific bounded cyclic tail-call graphs.

Selected jump, loop, iterator, and vararg instruction sites encode their control
operands into build-specific packets. Load, table access, table assignment,
comparison, arithmetic, closure creation, and vararg transfer semantics execute
inside generated semantic graphs where supported.
"""


def fmt_default(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return f"`{value}`"


def render_pass(name: str, info: dict) -> list[str]:
    contexts = " | ".join(get_pass_contexts(name))
    lines = [
        f"## {name}",
        f"**label:** {info['label']}  ",
        f"**group:** {info['group']} pass  ",
        f"**type:** {contexts}  ",
        "",
        PASS_DESCRIPTIONS.get(name, "No description available."),
        "",
    ]
    if name == "vm":
        lines.extend([VM_DETAILS, ""])
    return lines


def render_vm_options() -> list[str]:
    lines = ["## vm_options", ""]
    for name, info in VM_OPTION_DOCS.items():
        lines.extend([f"### {name}", "", info["description"], ""])
        values = info.get("values")
        if values:
            lines.extend(["| Value | Description |", "|---|---|"])
            for value, description in values:
                lines.append(f"| `{value}` | {description} |")
            lines.append("")
        if "range" in info:
            lines.extend([f"range: {info['range']}", ""])
        lines.extend([f"default: {fmt_default(info['default'])}", "", "---", ""])
    return lines


def render() -> str:
    lines = [
        "<!-- generated by tools/generate_config_docs.py; do not edit by hand -->",
        "",
        "# configuration",
        "",
        "## table of contents",
        "- [profiles](#profiles)",
        "- feature passes",
    ]
    for name in PASS_REGISTRY:
        lines.append(f"  - [{name}](#{name})")
    lines.append("- [vm_options](#vm_options)")
    for name in VM_OPTION_DOCS:
        lines.append(f"  - [{name}](#{name})")

    lines.extend([
        "",
        "## profiles",
        "The default config uses named profiles so test and release builds can switch",
        "without manually editing pass lists.",
        "",
        "```bash",
        "python main.py input.lua --profile dev",
        "python main.py input.lua --profile fast-vm",
        "python main.py input.lua --profile max",
        "python main.py input.lua --profile max --release-check",
        "```",
        "",
        "`--seed` is for reproducible test builds. `--release-check` rejects seeded",
        "builds and weak VM settings before writing release output.",
        "",
    ])

    for name, info in PASS_REGISTRY.items():
        lines.extend(render_pass(name, info))
    lines.extend(render_vm_options())
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="generate docs/configuration.md")
    parser.add_argument("--check", action="store_true", help="fail if the document is not up to date")
    args = parser.parse_args()

    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print(f"{OUTPUT} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
